(() => {
'use strict';
// Numbers transcribed from the supplied paper; see CONTENT_SOURCES.md.
const retrieval={
 'MSR-VTT':[['VAST',49.3,43.7],['Triangle',54.8,51.9],['BaryBind',56.1,53.6]],
 'DiDeMo':[['VAST',49.5,48.2],['Triangle',54.6,52.2],['BaryBind',56.3,54.0]],
 'ActivityNet':[['VAST',51.4,46.8],['Triangle',59.6,54.4],['BaryBind',60.6,57.2]],
 'VATEX':[['VAST',80.0,77.3],['Triangle',84.0,80.1],['BaryBind',84.7,81.8]]
};
function table(id,headers,rows,caption){document.getElementById(id).innerHTML=`<div class="table-scroll" tabindex="0" role="region" aria-label="${caption}"><table><caption class="sr-only">${caption}</caption><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr class="${r[0]==='BaryBind'?'ours':''}">${r.map((v,i)=>`<${i?'td':'th'} ${i?'':'scope="row"'}>${typeof v==='number'?v.toFixed(1):v}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function updateRetrieval(){const key=document.getElementById('dataset').value,rows=retrieval[key];document.getElementById('retrieval-bars').innerHTML=rows.map(r=>`<div class="bar-group ${r[0]==='BaryBind'?'ours':''}"><div class="bar-label"><b>${r[0]}</b><span>${r[1].toFixed(1)} / ${r[2].toFixed(1)}</span></div><div class="bar-track" aria-hidden="true"><div class="bar-fill" style="width:${r[1]}%"></div></div><div class="bar-track" aria-hidden="true"><div class="bar-fill v2t" style="width:${r[2]}%"></div></div></div>`).join('')+'<div class="bar-legend"><span><i></i>T2V · upper bar</span><span><i></i>V2T · lower bar</span><span>Scale: 0–100%</span></div>';document.getElementById('gap-bary').textContent=Math.abs(rows[2][1]-rows[2][2]).toFixed(1);document.getElementById('gap-baseline').textContent=Math.abs(rows[0][1]-rows[0][2]).toFixed(1)+' points · VAST';table('retrieval-table',['Method','T2V R@1 ↑','V2T R@1 ↑'],rows,`${key} zero-shot retrieval, T-VA, paper Table 2`);}
document.getElementById('dataset').addEventListener('change',updateRetrieval);updateRetrieval();
table('classification-table',['Method','Input','Acc@1 ↑','Acc@5 ↑'],[['VAST','A',40.3,71.7],['BaryBind','A',45.7,75.2],['VAST','V',46.3,72.7],['BaryBind','V',48.3,76.4],['GRAM','A+V',42.3,76.4],['Triangle','A+V',44.8,80.0],['OmniBind','A+V',46.2,76.2],['VAST','A+V',48.1,79.6],['BaryBind','A+V',55.6,83.4]],'VGGSound5K zero-shot classification, Table 1');
table('scalability-table',['Method','Modalities','MSR-VTT T2V / V2T','VATEX T2V / V2T'],[['BaryBind','T-V','54.2 / 52.0','82.9 / 80.4'],['BaryBind','T-VA','56.1 / 53.6','84.7 / 81.8'],['BaryBind','T-VAS','57.1 / 53.8','85.5 / 84.3'],['BaryBind','T-VASD','57.8 / 54.6','86.1 / 85.4'],['VAST','T-VASD','51.2 / 48.3','82.4 / 79.2'],['GRAM','T-VASD','54.9 / 51.3','83.8 / 82.1']],'Increasing modality count, paper Table 2');
table('compute-table',['Model','Parameters','Forward + backward','Time / epoch'],[['VAST','1.28B','~8.8 s','~5.7 h'],['GRAM','1.30B','~9.4 s','~6.1 h'],['BaryBind','1.34B','~9.7 s','~6.3 h']],'Training overhead, paper Table 19');
table('generation-table',['Method','T2I ↓','A2I ↓','TA2I ↓'],[['ImageBind',50.1,53.6,46.8],['VAST',48.1,57.2,50.6],['GRAM',46.7,56.5,45.2],['Triangle',46.4,54.5,44.3],['BaryBind',43.6,50.3,38.6]],'Cross-modal generation FID, Table 24');
const tabs=[...document.querySelectorAll('[role=tab]')];function setTab(tab){tabs.forEach(t=>{const selected=t===tab;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1;document.getElementById(t.getAttribute('aria-controls')).hidden=!selected;});}tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>setTab(tab));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(index+1)%tabs.length;if(e.key==='ArrowLeft')next=(index-1+tabs.length)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();setTab(tabs[next]);tabs[next].focus();}});});
document.querySelectorAll('[data-inference]').forEach(b=>b.addEventListener('click',()=>{const audio=b.dataset.inference==='a';document.querySelectorAll('[data-inference]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));document.getElementById('missing-score').textContent=audio?'49.4 / 78.3':'55.6 / 83.4';document.getElementById('missing-base').textContent=audio?'VAST: 40.8 / 71.6':'VAST: 48.1 / 79.6';}));
const cases={cooking:{query:'“A man is cooking in the kitchen.”',results:[['VIDEO',['A man is cooking in the kitchen','Video8834'],['A man chopping lobster and taking off the shell','Video9687']],['AUDIO',['Broth is being added to a soup pot and stirred with a rubber spatula','Video7376'],['A man is cooking in the kitchen','Video8834']],['SUBTITLE',['A person is cooking on stage','Video7362'],['The man is making a sauce in the kitchen','Video8772']]]},basketball:{query:'Video query: a basketball event.',results:[['TEXT',['People are playing basketball','Video7763'],['A player is putting a basketball into the basket from distance','Video9029']],['AUDIO',['People are playing basketball','Video7763'],['Basketball players making a shot in the last seven seconds','Video8124']],['SUBTITLE',['Basketball players making a shot in the last seven seconds','Video8124'],['A man runs into the crowd when trying to catch a basketball','Video8652']]]}};
function setQuery(key){const c=cases[key];document.getElementById('query-text').textContent=c.query;document.getElementById('consensus-results').innerHTML=c.results.map(r=>`<div><h4>WB → ${r[0]}</h4>${r.slice(1).map(p=>`<p>${p[0]}<small>${p[1]}</small></p>`).join('')}</div>`).join('');}
document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-query]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));setQuery(b.dataset.query);}));setQuery('cooking');
document.getElementById('copy-citation').addEventListener('click',async()=>{const text=document.getElementById('bibtex').textContent;let success=false;try{if(navigator.clipboard){await navigator.clipboard.writeText(text);success=true;}}catch{}if(!success){const input=document.createElement('textarea');input.value=text;input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();try{success=document.execCommand('copy');}catch{}input.remove();document.getElementById('copy-citation').focus();}document.getElementById('copy-status').textContent=success?'BibTeX copied.':'Select the citation text above to copy it.';});
const header=document.getElementById('header');window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>20),{passive:true});
})();
