pip install torch==2.0.1 
pip install torchvision==0.15.2 
pip install torchaudio==2.0.2 
pip install decord 
pip install h5py 
pip install ffmpeg-python 
pip install yacs 
pip install toolz 
pip install ipdb 
pip install einops 
pip install easydict 
pip install transformers==4.31.0 
pip install webdataset 
pip install SentencePiece 
pip install tqdm
pip install opencv-python==4.11.0.86
pip install audioread
pip install librosa
pip install wandb
pip install numpy==1.26.4
